/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;

import javax.swing.JOptionPane;

import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

import java.util.List;

import java.io.File; // Import the File class
import java.io.FileNotFoundException; // Import this class to handle errors
import java.text.SimpleDateFormat;
import java.util.Scanner;

/**
 *
 * @author Chilakalapudi
 */
public class HomePage extends javax.swing.JFrame {

	/**
	 * Creates new form HomeJFrame
	 */
	public HomePage() {
		initComponents();
		// display on center of window
		setSize(1400, 750);
		//setResizable(true);
		setLocationRelativeTo(null);
		String showname=jComboBox1.getSelectedItem().toString();
		String dateval = "" + model.getValue();
		String[] datearray = dateval.split(" ");
		String strdate = datearray[1] + "-" + datearray[2] + "-" + datearray[5];
		String searchkey=showname+","+strdate;
		System.out.println("searchkey:"+searchkey);
		populateBoxes(searchkey);
		// getContentPane().setBackground(Color.LIGHT_GRAY);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		// jTextField1 = new javax.swing.JTextField();

		model = new UtilDateModel();
		
		model.setDate(2023, 7, 18);
		model.setSelected(true);
		Properties p = new Properties();
		p.put("text.today", "Today");
		p.put("text.month", "Month");
		p.put("text.year", "Year");
		JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
		JDatePickerImpl datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
		
		
		
		
		jLabel2 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTextArea5 = new javax.swing.JTextArea();
		jPanel4 = new javax.swing.JPanel();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jPanel5 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jScrollPane6 = new javax.swing.JScrollPane();
		jTextArea6 = new javax.swing.JTextArea();
		jScrollPane7 = new javax.swing.JScrollPane();
		jTextArea7 = new javax.swing.JTextArea();
		jScrollPane8 = new javax.swing.JScrollPane();
		jTextArea8 = new javax.swing.JTextArea();
		jScrollPane10 = new javax.swing.JScrollPane();
		jTextArea10 = new javax.swing.JTextArea();
		jScrollPane9 = new javax.swing.JScrollPane();
		jTextArea9 = new javax.swing.JTextArea();
		jPanel8 = new javax.swing.JPanel();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jTextField10 = new javax.swing.JTextField();
		jTextField11 = new javax.swing.JTextField();
		jPanel9 = new javax.swing.JPanel();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jPanel10 = new javax.swing.JPanel();
		jButton11 = new javax.swing.JButton();
		jTextField12 = new javax.swing.JTextField();
		jButton12 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 51, 204));
		setResizable(false);
		setSize(new java.awt.Dimension(6, 0));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("DATE");

		/*
		 * jTextField1.addActionListener(new java.awt.event.ActionListener() { public
		 * void actionPerformed(java.awt.event.ActionEvent evt) {
		 * jTextField1ActionPerformed(evt); } });
		 */

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("SHOW NAME");

		List<String> shownameslist = new ArrayList<String>();
		
		try {
			File myObj = new File("shownames.txt");
			Scanner myReader = new Scanner(myObj);
			while (myReader.hasNextLine()) {
				String data = myReader.nextLine();
				shownameslist.add(data);
			}
			myReader.close();
		} catch (FileNotFoundException e) {
			System.out.println("An error occurred.");
			e.printStackTrace();
		}

		String[] strnames = (String[]) shownameslist.toArray(new String[shownameslist.size()]);
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(strnames));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});
		
		
		
		jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("SPARKS");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2).addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
						.addContainerGap()));

		jPanel2.setAlignmentX(50.0F);
		jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jPanel2.setLayout(new java.awt.GridLayout(1, 5, 20, 20));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("1");
		jPanel2.add(jLabel4);

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel5.setText("2");
		jPanel2.add(jLabel5);

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setText("3");
		jPanel2.add(jLabel6);

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel7.setText("4");
		jPanel2.add(jLabel7);

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel8.setText("5");
		jPanel2.add(jLabel8);

		jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 50));
		jPanel3.setAlignmentX(5.0F);
		jPanel3.setAlignmentY(5.0F);		
		jPanel3.setLayout(new java.awt.GridLayout(1, 5, 100, 100));

		jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane1.setAutoscrolls(true);
		jScrollPane1.setPreferredSize(new java.awt.Dimension(20, 20));

		jTextArea1.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea1.setColumns(5);
		jTextArea1.setRows(700);
		jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,1);
			}
		});
		jScrollPane1.setViewportView(jTextArea1);

		jPanel3.add(jScrollPane1);

		jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		jScrollPane2.setAutoscrolls(true);
		jScrollPane2.setPreferredSize(new java.awt.Dimension(66, 96));

		jTextArea2.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea2.setColumns(20);
		jTextArea2.setRows(700);
		jTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,2);
			}
		});
		jScrollPane2.setViewportView(jTextArea2);

		jPanel3.add(jScrollPane2);

		jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		jScrollPane3.setAutoscrolls(true);

		jTextArea3.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea3.setColumns(20);
		jTextArea3.setRows(700);
		jTextArea3.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,3);
			}
		});
		jScrollPane3.setViewportView(jTextArea3);

		jPanel3.add(jScrollPane3);

		jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		jScrollPane4.setAutoscrolls(true);

		jTextArea4.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea4.setColumns(20);
		jTextArea4.setRows(700);
		jTextArea4.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,4);
			}
		});
		jScrollPane4.setViewportView(jTextArea4);

		jPanel3.add(jScrollPane4);

		jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		jScrollPane5.setAutoscrolls(true);

		jTextArea5.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea5.setColumns(20);
		jTextArea5.setRows(700);
		jTextArea5.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,5);
			}
		});
		jScrollPane5.setViewportView(jTextArea5);

		jPanel3.add(jScrollPane5);

		jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
		jPanel4.setLayout(new java.awt.GridLayout(1, 5, 50, 0));

		jTextField2.setBackground(new java.awt.Color(255, 255, 102));
		jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel4.add(jTextField2);

		jTextField3.setBackground(new java.awt.Color(255, 255, 102));
		jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel4.add(jTextField3);

		jTextField4.setBackground(new java.awt.Color(255, 255, 102));
		jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel4.add(jTextField4);

		jTextField5.setBackground(new java.awt.Color(255, 255, 102));
		jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel4.add(jTextField5);

		jTextField6.setBackground(new java.awt.Color(255, 255, 102));
		jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel4.add(jTextField6);

		jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 40));
		jPanel5.setLayout(new java.awt.GridLayout(1, 0, 100, 0));

		jButton1.setBackground(new java.awt.Color(51, 102, 255));
		jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("Total");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel5.add(jButton1);

		jButton2.setBackground(new java.awt.Color(51, 102, 255));
		jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton2.setForeground(new java.awt.Color(255, 255, 255));
		jButton2.setText("Total");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel5.add(jButton2);

		jButton3.setBackground(new java.awt.Color(51, 102, 255));
		jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton3.setForeground(new java.awt.Color(255, 255, 255));
		jButton3.setText("Total");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel5.add(jButton3);

		jButton4.setBackground(new java.awt.Color(51, 102, 255));
		jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton4.setForeground(new java.awt.Color(255, 255, 255));
		jButton4.setText("Total");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jPanel5.add(jButton4);

		jButton5.setBackground(new java.awt.Color(51, 102, 255));
		jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton5.setForeground(new java.awt.Color(255, 255, 255));
		jButton5.setText("Total");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jPanel5.add(jButton5);

		jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
		jPanel6.setAlignmentX(50.0F);
		jPanel6.setAlignmentY(100.0F);
		jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jPanel6.setLayout(new java.awt.GridLayout(1, 5, 20, 20));

		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel9.setText("6");
		jPanel6.add(jLabel9);

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel10.setText("7");
		jPanel6.add(jLabel10);

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel11.setText("8");
		jPanel6.add(jLabel11);

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel12.setText("9");
		jPanel6.add(jLabel12);

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel13.setText("0");
		jPanel6.add(jLabel13);

		jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 50));
		jPanel7.setLayout(new java.awt.GridLayout(1, 5, 100, 100));

		jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane6.setAutoscrolls(true);
		jScrollPane6.setPreferredSize(new java.awt.Dimension(20, 20));

		jTextArea6.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea6.setColumns(5);
		jTextArea6.setRows(50);
		jTextArea6.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,6);
			}
		});
		jScrollPane6.setViewportView(jTextArea6);

		jPanel7.add(jScrollPane6);

		jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		jScrollPane7.setAutoscrolls(true);
		jScrollPane7.setPreferredSize(new java.awt.Dimension(66, 96));

		jTextArea7.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea7.setColumns(20);
		jTextArea7.setRows(50);
		jTextArea7.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,7);
			}
		});
		jScrollPane7.setViewportView(jTextArea7);

		jPanel7.add(jScrollPane7);

		jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane8.setAutoscrolls(true);
		jScrollPane8.setPreferredSize(new java.awt.Dimension(20, 20));

		jTextArea8.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea8.setColumns(5);
		jTextArea8.setRows(50);
		jTextArea8.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,8);
			}
		});
		jScrollPane8.setViewportView(jTextArea8);

		jPanel7.add(jScrollPane8);

		jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane10.setAutoscrolls(true);
		jScrollPane10.setPreferredSize(new java.awt.Dimension(20, 20));

		jTextArea10.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea10.setColumns(5);
		jTextArea10.setRows(50);
		jTextArea10.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,9);
			}
		});
		jScrollPane10.setViewportView(jTextArea10);

		jPanel7.add(jScrollPane10);

		jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane9.setAutoscrolls(true);
		jScrollPane9.setPreferredSize(new java.awt.Dimension(20, 20));

		jTextArea9.setBackground(new java.awt.Color(255, 204, 204));
		jTextArea9.setColumns(5);
		jTextArea9.setRows(50);
		jTextArea9.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextAreaKeyPressed(evt,0);
			}
		});
		jScrollPane9.setViewportView(jTextArea9);

		jPanel7.add(jScrollPane9);

		jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
		jPanel8.setLayout(new java.awt.GridLayout(1, 5, 50, 0));

		jTextField7.setBackground(new java.awt.Color(255, 255, 102));
		jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel8.add(jTextField7);

		jTextField8.setBackground(new java.awt.Color(255, 255, 102));
		jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel8.add(jTextField8);

		jTextField9.setBackground(new java.awt.Color(255, 255, 102));
		jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel8.add(jTextField9);

		jTextField10.setBackground(new java.awt.Color(255, 255, 102));
		jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel8.add(jTextField10);

		jTextField11.setBackground(new java.awt.Color(255, 255, 102));
		jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanel8.add(jTextField11);

		jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 40));
		jPanel9.setLayout(new java.awt.GridLayout(1, 5, 100, 0));

		jButton6.setBackground(new java.awt.Color(51, 102, 255));
		jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton6.setForeground(new java.awt.Color(255, 255, 255));
		jButton6.setText("Total");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jPanel9.add(jButton6);

		jButton7.setBackground(new java.awt.Color(51, 102, 255));
		jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton7.setForeground(new java.awt.Color(255, 255, 255));
		jButton7.setText("Total");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jPanel9.add(jButton7);

		jButton8.setBackground(new java.awt.Color(51, 102, 255));
		jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton8.setForeground(new java.awt.Color(255, 255, 255));
		jButton8.setText("Total");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		jPanel9.add(jButton8);

		jButton9.setBackground(new java.awt.Color(51, 102, 255));
		jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton9.setForeground(new java.awt.Color(255, 255, 255));
		jButton9.setText("Total");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});
		jPanel9.add(jButton9);

		jButton10.setBackground(new java.awt.Color(51, 102, 255));
		jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton10.setForeground(new java.awt.Color(255, 255, 255));
		jButton10.setText("Total");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});
		jPanel9.add(jButton10);

		jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));

		jButton11.setBackground(new java.awt.Color(255, 204, 102));
		jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jButton11.setForeground(new java.awt.Color(255, 255, 255));
		jButton11.setText("Total");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jTextField12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jTextField12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField12ActionPerformed(evt);
			}
		});

		jButton12.setBackground(new java.awt.Color(0, 204, 0));
		jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jButton12.setForeground(new java.awt.Color(255, 255, 255));
		jButton12.setText("Print");
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});
		
		datePicker.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				
				String showname=jComboBox1.getSelectedItem().toString();
				String dateval = "" + model.getValue();
				String[] datearray = dateval.split(" ");
				String strdate = datearray[1] + "-" + datearray[2] + "-" + datearray[5];
				String searchkey=showname+","+strdate;
				System.out.println("datePicker > searchkey:"+searchkey);
				populateBoxes(searchkey);
			}
		});
		

		 javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
	        jPanel10.setLayout(jPanel10Layout);
	        jPanel10Layout.setHorizontalGroup(
	            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel10Layout.createSequentialGroup()
	                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
	        );
	        jPanel10Layout.setVerticalGroup(
	            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
	            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
	            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        );


		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		 layout.setHorizontalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
		                .addContainerGap()
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		                .addContainerGap())
		        );
		        layout.setVerticalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(layout.createSequentialGroup()
		                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addGap(26, 26, 26)
		                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addGap(33, 33, 33)
		                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		        );
		pack();
	}// </editor-fold>//GEN-END:initComponents

	/*
	 * private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
	 * {//GEN-FIRST:event_jTextField1ActionPerformed // TODO add your handling code
	 * here: }//GEN-LAST:event_jTextField1ActionPerformed
	 */

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox1ActionPerformed

	private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField12ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField12ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea1.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField2.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea2.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField3.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea3.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField4.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea4.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField5.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea5.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField6.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea6.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField7.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton6ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea7.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField8.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton7ActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea8.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField9.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton8ActionPerformed

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea10.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField10.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton9ActionPerformed

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
		// TODO add your handling code here:
		try {
			String text1 = jTextArea9.getText();
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			jTextField11.setText("" + text1sum);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Please check your inputs!");
		}
	}// GEN-LAST:event_jButton10ActionPerformed

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton11ActionPerformed
		// TODO add your handling code here:
		String text2sum = jTextField2.getText();
		String text3sum = jTextField3.getText();
		String text4sum = jTextField4.getText();
		String text5sum = jTextField5.getText();
		String text6sum = jTextField6.getText();
		String text7sum = jTextField7.getText();
		String text8sum = jTextField8.getText();
		String text9sum = jTextField9.getText();
		String text10sum = jTextField10.getText();
		String text11sum = jTextField11.getText();
		Double sum = 0.0;
		sum += getDoubleVal(text2sum) + getDoubleVal(text3sum) + getDoubleVal(text4sum) + getDoubleVal(text5sum)
				+ getDoubleVal(text6sum) + getDoubleVal(text7sum) + getDoubleVal(text8sum) + getDoubleVal(text9sum)
				+ getDoubleVal(text10sum) + getDoubleVal(text11sum);
		jTextField12.setText("" + sum);
	}// GEN-LAST:event_jButton11ActionPerformed

	public Double getDoubleVal(String s) {
		Double result = 0.0;
		if (s != null && !s.isEmpty()) {
			result = Double.valueOf(s);
		}
		return result;
	}

	  
	
	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton12ActionPerformed
		// TODO add your handling code here:
		// Print button
		try {
			String text2 = jTextArea1.getText();
			String text3 = jTextArea2.getText();
			String text4 = jTextArea3.getText();
			String text5 = jTextArea4.getText();
			String text6 = jTextArea5.getText();
			String text7 = jTextArea6.getText();
			String text8 = jTextArea7.getText();
			String text9 = jTextArea8.getText();
			String text10 = jTextArea9.getText();
			String text11 = jTextArea10.getText();
			String[] box1 = text2.split("\n");
			String[] box2 = text3.split("\n");
			String[] box3 = text4.split("\n");
			String[] box4 = text5.split("\n");
			String[] box5 = text6.split("\n");
			String[] box6 = text7.split("\n");
			String[] box7 = text8.split("\n");
			String[] box8 = text9.split("\n");
			String[] box9 = text11.split("\n");
			String[] box0 = text10.split("\n");
			int maxsize = 0;
			if (box1.length > maxsize) {
				maxsize = box1.length;
			}
			if (box2.length > maxsize) {
				maxsize = box2.length;
			}
			if (box3.length > maxsize) {
				maxsize = box3.length;
			}
			if (box4.length > maxsize) {
				maxsize = box4.length;
			}
			if (box5.length > maxsize) {
				maxsize = box5.length;
			}
			if (box6.length > maxsize) {
				maxsize = box6.length;
			}
			if (box7.length > maxsize) {
				maxsize = box7.length;
			}
			if (box8.length > maxsize) {
				maxsize = box8.length;
			}
			if (box9.length > maxsize) {
				maxsize = box9.length;
			}
			if (box0.length > maxsize) {
				maxsize = box0.length;
			}

			String text2sum = jTextField2.getText();
			String text3sum = jTextField3.getText();
			String text4sum = jTextField4.getText();
			String text5sum = jTextField5.getText();
			String text6sum = jTextField6.getText();
			String text7sum = jTextField7.getText();
			String text8sum = jTextField8.getText();
			String text9sum = jTextField9.getText();
			String text10sum = jTextField10.getText();
			String text11sum = jTextField11.getText();
			String texttotal = jTextField12.getText();
			String dateval = "" + model.getValue();
			String name = jComboBox1.getSelectedItem().toString();
			System.out.println("dateval:" + dateval);

			String[] datearray = dateval.split(" ");
			String newstringdate = datearray[1] + "-" + datearray[2] + "-" + datearray[5];

			PrintPDF.print(box1, box2, box3, box4, box5, box6, box7, box8, box9, box0, maxsize, text2sum, text3sum,
					text4sum, text5sum, text6sum, text7sum, text8sum, text9sum, text10sum, text11sum, texttotal, name,
					newstringdate);

			JOptionPane.showMessageDialog(this, "PDF Saved in D:/ drive");
		} catch (Exception ex) {
			System.out.println(ex);
			ex.printStackTrace();
		}
	}// GEN-LAST:event_jButton12ActionPerformed

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
		String showname=jComboBox1.getSelectedItem().toString();
		String dateval = "" + model.getValue();
		String[] datearray = dateval.split(" ");
		String strdate = datearray[1] + "-" + datearray[2] + "-" + datearray[5];
		String searchkey=showname+","+strdate;
		System.out.println("searchkey:"+searchkey);
		populateBoxes(searchkey);
    }  
	public void populateBoxes(String searchKey) {
		try {
			String dataLine=PrintPDF.retrieveData(searchKey);
			System.out.println("dataLine:"+dataLine);
			if(dataLine!="") {
				String[] data=dataLine.split(",");
				String box1data=getBoxData(data[2]);
				String box2data=getBoxData(data[3]);
				String box3data=getBoxData(data[4]);
				String box4data=getBoxData(data[5]);
				String box5data=getBoxData(data[6]);
				String box6data=getBoxData(data[7]);
				String box7data=getBoxData(data[8]);
				String box8data=getBoxData(data[9]);
				String box9data=getBoxData(data[10]);
				String box0data=getBoxData(data[11]);
				jTextArea1.setText(box1data);
				jTextArea2.setText(box2data);
				jTextArea3.setText(box3data);
				jTextArea4.setText(box4data);
				jTextArea5.setText(box5data);
				jTextArea6.setText(box6data);
				jTextArea7.setText(box7data);
				jTextArea8.setText(box8data);
				jTextArea9.setText(box9data);
				jTextArea10.setText(box0data);
				jTextField2.setText(data[12]);
				jTextField3.setText(data[13]);
				jTextField4.setText(data[14]);
				jTextField5.setText(data[15]);
				jTextField6.setText(data[16]);
				jTextField7.setText(data[17]);
				jTextField8.setText(data[18]);
				jTextField9.setText(data[19]);
				jTextField10.setText(data[20]);
				jTextField11.setText(data[21]);
				jTextField12.setText(data[22]);
				}else {
					jTextArea1.setText("");
					jTextArea2.setText("");
					jTextArea3.setText("");
					jTextArea4.setText("");
					jTextArea5.setText("");
					jTextArea6.setText("");
					jTextArea7.setText("");
					jTextArea8.setText("");
					jTextArea9.setText("");
					jTextArea10.setText("");
					jTextField2.setText("");
					jTextField3.setText("");
					jTextField4.setText("");
					jTextField5.setText("");
					jTextField6.setText("");
					jTextField7.setText("");
					jTextField8.setText("");
					jTextField9.setText("");
					jTextField10.setText("");
					jTextField11.setText("");
					jTextField12.setText("");
				}
		}catch(Exception ex) {
			ex.printStackTrace();
		}
	}
	public static String getBoxData(String data) {
		System.out.println("boxdata:"+data);
		String result="";
		 data=data.replace("\"[", "");
		data=data.replace("]\"","");
		if(data.contains(";")) {
		for(String s:data.split(";")) {
			s=s.trim();
			result+=s+"\n";
		}
		}else {
			result=data+"\n";
		}
		result=result.trim();
		return result;
	}
	
	
	private void jTextAreaKeyPressed(java.awt.event.KeyEvent evt,int box) {
		setBoxTotal(box);
		// TODO add your handling code here:
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			// code to send message goes here
			saveDatabase();
		}
	}
	
	
	public void setBoxTotal(int box){
		try {
			String text1="";
			if(box==1) {
				text1=jTextArea1.getText();
			}else if(box==2) {
				text1=jTextArea2.getText();
			}else if(box==3) {
				text1=jTextArea3.getText();
			}else if(box==4) {
				text1=jTextArea4.getText();
			}else if(box==5) {
				text1=jTextArea5.getText();
			}else if(box==6) {
				text1=jTextArea6.getText();
			}else if(box==7) {
				text1=jTextArea7.getText();
			}else if(box==8) {
				text1=jTextArea8.getText();
			}else if(box==9) {
				text1=jTextArea10.getText();
			}else if(box==0) {
				text1=jTextArea9.getText();
			}
			Double text1sum = 0.0;
			if (text1 != null) {
				if (text1.contains("\n")) {
					for (String s : text1.split("\n")) {
						s = s.trim();
						text1sum += Double.valueOf(s);
					}
				} else {
					text1sum += Double.valueOf(text1);
				}
			}
			if(box==1) {
				jTextField2.setText("" + text1sum);
			}else if(box==2) {
				jTextField3.setText("" + text1sum);
			}else if(box==3) {
				jTextField4.setText("" + text1sum);
			}else if(box==4) {
				jTextField5.setText("" + text1sum);
			}else if(box==5) {
				jTextField6.setText("" + text1sum);
			}else if(box==6) {
				jTextField7.setText("" + text1sum);
			}else if(box==7) {
				jTextField8.setText("" + text1sum);
			}else if(box==8) {
				jTextField9.setText("" + text1sum);
			}else if(box==9) {
				jTextField10.setText("" + text1sum);
			}else if(box==0) {
				jTextField11.setText("" + text1sum);
			}
			String text2sum = jTextField2.getText();
			String text3sum = jTextField3.getText();
			String text4sum = jTextField4.getText();
			String text5sum = jTextField5.getText();
			String text6sum = jTextField6.getText();
			String text7sum = jTextField7.getText();
			String text8sum = jTextField8.getText();
			String text9sum = jTextField9.getText();
			String text10sum = jTextField10.getText();
			String text11sum = jTextField11.getText();
			Double sum = 0.0;
			sum += getDoubleVal(text2sum) + getDoubleVal(text3sum) + getDoubleVal(text4sum) + getDoubleVal(text5sum)
					+ getDoubleVal(text6sum) + getDoubleVal(text7sum) + getDoubleVal(text8sum) + getDoubleVal(text9sum)
					+ getDoubleVal(text10sum) + getDoubleVal(text11sum);
			jTextField12.setText("" + sum);
			
		} catch (Exception ex) {
			//JOptionPane.showMessageDialog(this, "Please check your inputs!");
			System.out.println(ex);
			ex.printStackTrace();
		}
	}

	public void saveDatabase() {
		try {
			String text2 = jTextArea1.getText();
			String text3 = jTextArea2.getText();
			String text4 = jTextArea3.getText();
			String text5 = jTextArea4.getText();
			String text6 = jTextArea5.getText();
			String text7 = jTextArea6.getText();
			String text8 = jTextArea7.getText();
			String text9 = jTextArea8.getText();
			String text10 = jTextArea9.getText();
			String text11 = jTextArea10.getText();
			String[] box1 = text2.split("\n");
			String[] box2 = text3.split("\n");
			String[] box3 = text4.split("\n");
			String[] box4 = text5.split("\n");
			String[] box5 = text6.split("\n");
			String[] box6 = text7.split("\n");
			String[] box7 = text8.split("\n");
			String[] box8 = text9.split("\n");
			String[] box9 = text11.split("\n");
			String[] box0 = text10.split("\n");
			int maxsize = 0; // random value

			String text2sum = jTextField2.getText();
			String text3sum = jTextField3.getText();
			String text4sum = jTextField4.getText();
			String text5sum = jTextField5.getText();
			String text6sum = jTextField6.getText();
			String text7sum = jTextField7.getText();
			String text8sum = jTextField8.getText();
			String text9sum = jTextField9.getText();
			String text10sum = jTextField10.getText();
			String text11sum = jTextField11.getText();
			String texttotal = jTextField12.getText();
			String dateval = "" + model.getValue();
			String name = jComboBox1.getSelectedItem().toString();
			System.out.println("dateval:" + dateval);
			String[] datearray = dateval.split(" ");
			String newstringdate = datearray[1] + "-" + datearray[2] + "-" + datearray[5];
			System.out.println(newstringdate); // 2011-01-18
			PrintPDF.saveData(box1, box2, box3, box4, box5, box6, box7, box8, box9, box0, maxsize, text2sum, text3sum,
					text4sum, text5sum, text6sum, text7sum, text8sum, text9sum, text10sum, text11sum, texttotal, name,
					newstringdate);
		} catch (Exception ex) {
			System.out.println(ex);
			ex.printStackTrace();
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomePage().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane10;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JScrollPane jScrollPane8;
	private javax.swing.JScrollPane jScrollPane9;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea10;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	private javax.swing.JTextArea jTextArea5;
	private javax.swing.JTextArea jTextArea6;
	private javax.swing.JTextArea jTextArea7;
	private javax.swing.JTextArea jTextArea8;
	private javax.swing.JTextArea jTextArea9;
	// private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	private UtilDateModel model;
	// End of variables declaration//GEN-END:variables
}
